#!/bin/bash
#=======================================================================
#=====                                                             =====
#=====   runscript - Runs a unix script in the current directory   =====
#=====                                                             =====
#=======================================================================
#
# This shell script is used to submit a unix script to the
# batch facility.  Usage of runscript is as follows:
#
# run_script script_name
# 
# Send any problems with or suggestions about runscript to:
#***************************************************************************
# Dave Young
# HPC Computational Specialist
# Alabama Supercomputer Center
# 686 Discovery Dr.
# Huntsville, AL 35806
# Phone: (256) 971-7434
# email: hpc@asc.edu
#***************************************************************************
#
# This software is the intellectual property of CSRA (formerly CSC) or any company that may obtain the rights from CSRA.  
# The Alabama Supercomputer Authority has rights to continue using this software, but not to distribute it, 
# even if a different professional services contractor is contracted.  Subsequent contracting organizations may use and edit
# this software on behalf of the Alabama Supercomputer Authority, but may not distribute this or any modified version of it
# to their other customers.


#
#  Message of the Day
echo "This runs a script in the current directory via the queue system"
echo "This script lets the job use multiple processors on the same node."
echo "Report problems and post questions to the HPC staff (hpc@asc.edu)"
echo " "
pwddir=`pwd`
# if no parameters input, go to "Usage is..."
if test $# -ne 0
  then

# test for existence of script file
  if test -f $1
  then

# test if the script file is executable
if ! test -x $1
then
  echo "ERROR:  File $1 does not have execute permissions.  Set them with"
  echo "             chmod +x $1"
  echo " "
  exit
fi

# check for incorrect ./ in script name
dot_check=`echo "$1" | grep "\./" | wc -l`
if [ "$dot_check" -gt "0" ]
then
  echo "ERROR:  File $1 has a dot and slash in front of it"
  echo "        please submit without the ./"
  echo " "
  exit
fi

/scripts/check_ssh

# Call nqsquery to choose pbs parameters for calculation
# if you call with -s flag, it will list serial and route queues only
#/scripts/qquery -s
/scripts/qquery

if [ -f qfile ]
then
  read queue time memory sttime num_cpus < qfile
  #echo "WARNING: uncomment line to remove qfile later"
  rm qfile
else
  echo "ERROR: qfile not found"
  echo "       Make sure you have write permissions in this directory"
  exit
fi

num_temp=$((num_cpus+1))
num_nodes=$((num_temp/2))

#echo "num_cpus = "$num_cpus
#echo "num_nodes = "$num_nodes

#*********************** LOAD PREFERENCES ****************
# set defaults
job_name_pref=PROMPT
cluster_pref=PROMPT

# Read queue preferences if available.
if [ -f ~/.asc_queue ]
then
  # source preferences file
  source ~/.asc_queue
fi

# error trap for make it qsub argument
if [ "$cluster_pref" == "any" ]
then
  # asax only
  cluster_pref="asax"
fi

#**************** APPLICATION SPECIFIC *******************
# checks specific to application are put here
# For example, if they choose mutilple cpus, you could check
# that the input file has multiple cpu directive.

#
# Ask user for jobname
echo ""
def_jobname=$1"SCRIPT"
def_jobname2=`echo $def_jobname | tr -d '.' | tr -d '-' | tr -d '_' | cut -c1-18`

if [ "$job_name_pref" == "PROMPT" ]
then
  echo "Enter a name for your job (default: $def_jobname2)"
  read jobname
  if [ $jobname ]
  then
    junk="0"
  else
    jobname=$def_jobname2
  fi
elif [ "$job_name_pref" == "DEFAULT" ]
then
  jobname=$def_jobname2
  echo "The job name will be $jobname (can be changed in .asc_queue file)"
  echo
else
  jobname=$job_name_pref  
  echo "The job name will be $jobname (from your .asc_queue preferences file)"
  echo
fi


# get user name
userid=`whoami`
my_email=`head -1 ~/.forward`
#my_email=`cat ~/.forward | tr '\n' ',' | rev | cut -c2- | rev`

/scripts/special_queues $queue
extra_options=`cat qfile2`
rm qfile2
if [ "$extra_options" == "exit" ]
then
  exit
fi

#set_limits cpu_time num_nodes/NA cpus_per_node/NA mem lic/NA file/NA gpus/NA
#limits=`/scripts/set_limits $time NA $num_cpus $memory NA NA NA`
limits=`/scripts/set_limits $time NA $num_cpus $memory NA NA NA`

queue_test=$( echo $queue | grep gpu | wc -l )
if [ "$queue_test" -gt "0" ]
then
  echo " "
  echo "ERROR: use a gpu script to submit jobs to the gpu queue."
  echo " "
  exit
fi

#set_queue queue
#echo "calling set_queue $queue"
queue=`/scripts/set_queue $queue`

#constraints="--constraint=asax002"  # a specific node
#constraints="--constraint=x86-64"  # a specific cluster
# constraints="--constraint=icelake"  # a specific architecture
constraints="--constraint=ampere"  # a specific coprocessor

if [ "$cluster_pref" == "PROMPT" ]
then
  # ask what partition to run on
  echo "Run on;  icelake, milan, genoa (default: asax)"
  read partition

  if [ ! $partition ]
  then
    # asax only
    partition="asax"
  fi

else
  partition=$cluster_pref
  echo "Using cluster $partition per your .asc_queue file."
fi

constraints="--constraint="$partition  # a specific cluster

#echo " limits = "$limits
#echo " qos = "$qos


/scripts/check_constraints $constraints
if [ -f qfile4 ]
then
  read result < qfile4
  #echo "WARNING: uncomment line to remove qfile4 later"
  rm qfile4

  if [ $result == "fail" ]
  then
    exit
  fi
else
  echo "ERROR: qfile4 not found"
  echo "       Make sure you have write permissions in this directory"
  exit
fi

#echo "constraints sent to constraints_to_pbs $constraints"
constraints=$( /scripts/constraints_to_pbs $constraints )

#
#
# Echo settings
echo " "
echo "============================================================"
echo "=====         Summary of your script job               ====="
echo "============================================================"
echo "  The script file is: $1"
echo "  The time limit is $time HH:MM:SS."
echo "  The memory limit is: $memory"
echo "  The job will start running after: $sttime"
echo "  Job Name: $jobname" 
#echo "  Virtual queue: $queue"
echo "  Queue: $queue"
echo "  Constraints: $constraints"
#echo -n "Job number "
# Submit the job to the proper queue.
#

check_script $1

source /scripts/print_prologue

echo "  Queue submit command:"
echo "qsub $queue -j oe -N $jobname -a $sttime -r n -M $my_email ${limits}${constraints} $extra_options"
echo

qsub $queue -j oe -N $jobname -a $sttime -r n -M $my_email ${limits}${constraints} $extra_options <<END_QSUB | tee job_num.txt
#!/bin/bash
#
#echo "PBS_JOBID="\$PBS_JOBID

#  set the workdir variable

export asax_test=\`hostname | grep asax | wc -l\`
if [ "\$asax_test" == "1" ] 
then
  echo "setting asax scratch directory"
  export workdir=/scratch-local/${LOGNAME}.\${PBS_JOBNAME}.\${PBS_JOBID}
fi

#
echo " "
echo "============================================================"
echo "=====         Summary of your script job               ====="
echo "============================================================"
echo "  The script file is: $1"
echo "  The time limit is $time HH:MM:SS."
echo "  The target directory is: $pwddir"
echo "  The working directory is: " \$workdir
echo "  The memory limit is: $memory"
echo "  The job will start running after: $sttime"
echo "  Job Name: $jobname" 
#echo "  Virtual queue: $queue"
echo "  Queue: $queue"
echo "  Constraints: $constraints"
export FIRST_NODE=\`cat \$PBS_NODEFILE | head -1\`
export NUM_MASTER_NODE=\`cat \$PBS_NODEFILE | grep \$FIRST_NODE | wc -w\`
echo "  Using " \$NUM_MASTER_NODE " cores on master node " \$FIRST_NODE
echo "  Node list: " \`cat \$PBS_NODEFILE\`
export NODELIST=\`cat \$PBS_NODEFILE | wc -w\`
echo "  Cores: " \$NODELIST
echo "  Command typed:"
echo "$0 $1 $2 $3 $4 $5 $6"
echo "  Queue submit command:"
echo "qsub $queue -j oe -N $jobname -a $sttime -r n -M $my_email ${limits}${constraints} $extra_options"

source /apps/profiles/modules_asax.sh.dyn
module purge

if [ -d \$workdir ] 
then
  echo "Directory \$workdir already exists"
else
  mkdir \$workdir
fi


#
# Execute the program
#
export TMPDIR=\$workdir
export TEMPDIR=\$workdir
export OMP_NUM_THREADS=$num_cpus
export num_cpus=$num_cpus
export MV2_USE_THREAD_WARNING=0
cd $pwddir

if [ -f /scratch-local/\$PBS_JOBID.cpus.taskset ] 
then
  export taskset_cpu_list=\`cat /scratch-local/\$PBS_JOBID.cpus.taskset\`
  echo "using taskset with following CPU list"
  echo \$taskset_cpu_list
  /usr/bin/taskset -c \$taskset_cpu_list ./$1
else
  ./$1
fi

# cleanup temporary directory
cd $pwddir
# check if they cleaned up after themselves
if [ -d \$workdir ]
then
  if [ -f \$workdir/.NOPBSERASE ]
  then
    echo "ERROR: file \$workdir/.NOPBSERASE found"
  else
    rm -r \$workdir
  fi
fi

sleep 3

if [ -f /metrics/jobs/\${PBS_JOBID}.txt ]
then
  rm /metrics/jobs/\${PBS_JOBID}.txt
fi

job_num=\$( /usr/bin/echo \${PBS_JOBID} | /usr/bin/cut -f 1 -d '.' )
#echo "job_num=\${job_num}"
#echo "PBS_JOBID=\${PBS_JOBID}"
if [ -f /metrics/jobs/\${job_num}.txt ]
then
  #echo "deleting /metrics/jobs/\${job_num}.txt"
  rm /metrics/jobs/\${job_num}.txt
fi

exit 0
END_QSUB

source /scripts/name_prologue

  else

    echo "Could not find script file $pwddir"/$1 "in this directory."
    exit
  fi
else
  #echo " "
  echo " Usage is - run_script script_file  "
  echo " "
fi

